### ISSUE TITLE
how to run? error when trying to

### ISSUE THREAD

**Issue by dragonGRaf** [Lozarth/Disboard-Auto-Bump-Selfbot#3]
tried node bot.js 

`[opc@discord-bot-servers Bump]$ node bot.js
node:internal/modules/cjs/loader:1029
  throw err;
  ^

Error: Cannot find module 'node-yaml-config'
Require stack:
- /home/opc/dragon/Bump/bot.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/opc/dragon/Bump/bot.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/opc/dragon/Bump/bot.js' ]`

**Comment by spaxh** [comment]
Use in console `npm i` to install dependencies. a new version will be released with dotenv for better security.

**Comment by dragonGRaf** [comment]
> Use in console `npm i` to install dependencies. a new version will be released with dotenv for better security.

used that but still didnt start
i want to use my linux server for this
`[opc@discord-bot-servers Bump]$ node bot.js
node:internal/modules/cjs/loader:1031
  throw err;
  ^

Error: Cannot find module 'node-yaml-config'
Require stack:
- /home/opc/dragon/Bump/bot.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/opc/dragon/Bump/bot.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/opc/dragon/Bump/bot.js' ]`
``

**Comment by spaxh** [comment]
install new version of code and install dependencies

**Comment by dragonGRaf** [comment]
> install new version of code and install dependencies

i did as i wrote before + the "new" code is 2 weeks and last code i downloaded and installed dependencies was 4 days ago

**Comment by spaxh** [comment]
Your platform and linux?
